os:
# TODO(dantup): Tests fail on Linux
# 00:58+0 -1: test/integration_test.dart: integration (setUpAll)[E]
# SocketException: OS Error: Connection refused, errno = 111, address = localhost, port = 45924
# - linux
  - osx

addons:
  chrome: stable

env:
  global:
    - BOT=main
    - BOT=test_ddc
    - BOT=test_dart2js
    - BOT=flutter_sdk_tests
  matrix:
    - DART_CHANNEL=stable/release
    - DART_CHANNEL=dev/raw

script: ./tool/travis.sh

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.pub-cache
