os:
  - linux
  - osx

addons:
  chrome: stable

env:
  - DART_CHANNEL=dev/raw BOT=main
  - DART_CHANNEL=dev/raw BOT=test_ddc
  - DART_CHANNEL=dev/raw BOT=test_dart2js
  - DART_CHANNEL=dev/raw BOT=flutter_sdk_tests
  # Disable testing on stable; it creates many more bots, and we generally only need
  # test coverage for the SDK version we're developing and distributing against.
  # - DART_CHANNEL=stable/release BOT=main
  # - DART_CHANNEL=stable/release BOT=test_ddc
  # - DART_CHANNEL=stable/release BOT=test_dart2js
  # - DART_CHANNEL=stable/release BOT=flutter_sdk_tests

script: ./tool/travis.sh

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.pub-cache
